### ISSUE TITLE
Error setting up Kubernetes dashboard 

### ISSUE THREAD

**Issue by avi1810** [open-ness/specs#10]
The kube dashboard pod does not run . 
![kub](https://user-images.githubusercontent.com/61222801/74807857-82a9c380-530f-11ea-95c4-ea4d622ede41.PNG)

**Comment by amr-mokhtar** [comment]
Is that happening when following the steps in [Installing Kubernetes Dashboard](https://github.com/otcshare/specs/blob/master/doc/getting-started/network-edge/controller-edge-node-setup.md#installing-kubernetes-dashboard)? Can you also confirm the kubernetes version on your setup?

**Comment by avi1810** [comment]
First i ran the cleanup and then the deploy ne script. After that when i
try to deploy the kubernetes dashboard,it gets created but I cannot access
the dashboard and then i saw the pods and it shows that error creating the
pod. The above screenshot is the the output of kubectl decribe pod
kubernetes-dashboard
Please help

**Comment by amr-mokhtar** [comment]
Can you provide more details so that we can help?

- At which step it fails?
- Did it work with you at least once before you cleaned up?
- What is the kubernetes version?
- Can you share the status of all pods and the full printout of the kubectl describe?
- What are the exact steps to be followed in order to reproduce the error?

**Comment by avi1810** [comment]
- The scripts cleanup_ne.sh and deploy_ne.sh ran successfully. Then i tried installing kubernetes dashboard . The dashboard is not getting installed

- Kubernets version 1.16.2

-

**Comment by avi1810** [comment]
Thanks for  the response Amr. I was making some mistake on my side
