### ISSUE TITLE
OpenVINO host and client setup

### ISSUE THREAD

**Issue by sucoderssaince** [open-ness/specs#13]
Please provide the steps regarding how to setup the client simulator. I am facing issues everytime while running the command 'kubectl interfaceservice attach <edge_node_host_name> 0000:86:00.0'. As soon as the command is run, the node becomes unreachable. Basically we are not clear about setting the network interface. Please provide the detailed overview.

**Comment by amr-mokhtar** [comment]
Hi @sucoderssaince,
The `interfaceservice` kubectl plugin user's guide is provided at [OpenNESS Interface Service](https://github.com/otcshare/specs/blob/master/doc/applications-onboard/openness-interface-service.md) page. Probably the node is becoming unreachable because the provided PCI BDF is the one which in use for management. What you need to do is:
1. find which PCI BDF maps to the physical eth interface that is intended for use with the dataplane
```shell
kubectl interfaceservice get <node_hostname>
```
2. use `interfaceservice` to attach that physical interface:
```shell
kubectl interfaceservice attach <node_hostname> <BDF-connected-to-dataplane>
```
Note that in a MEC deployment, each Edge node should have two physical interfaces:
1. management/control-plane interface (this is the interface which is connected to your lab network and the one that Kubernetes master is communicating through with the Edge node)
2. data-plane interface (this is the one that should be attached, i.e: bridged with OVN)

Good examples of using `interfaceservice` are provided with [OpenVINO app](https://github.com/otcshare/specs/blob/master/doc/applications-onboard/network-edge-applications-onboarding.md#setting-up-networking-interfaces) and [SmartCity app](https://github.com/otcshare/specs/blob/master/doc/applications-onboard/network-edge-applications-onboarding.md#installing-openness).
